export const regions = [
    {label: "NA", value: "na", server: "na1", description: "North America"},
    {label: "EUW", value: "euw", server: "euw1", description: "Europe West"},
    {label: "EUNE", value: "eun", server: "eun1", description: "Europe Nordic & East"},
    {label: "KR", value: "kr", server: "kr", description: "Republic of Korea"},
    {label: "JP", value: "jp", server: "jp1", description: "Japan"},
    {label: "OCE", value: "oce", server: "oc1", description: "Oceania"},
    {label: "TW", value: "tw", server: "tw2", description: "Taiwan, Hong Kong, and Macao"},
    {label: "PH", value: "ph", server: "ph2", description: "The Philippines"},
    {label: "SG", value: "sg", server: "sg2", description: "Singapore, Malaysia, & Indonesia"},
    {label: "TH", value: "th", server: "th2", description: "Thailand"},
    {label: "VN", value: "vn", server: "vn2", description: "Vietnam"},  
    {label: "BR", value: "br", server: "br1", description: "Brazil"},
    {label: "LAN", value: "lan", server: "la1", description: "Latin America North"},
    {label: "LAS", value: "las", server: "la2", description: "Latin America South"},
    {label: "RU", value: "ru", server: "ru1", description: "Russia"},
    {label: "TR", value: "tr", server: "tr1", description: "Turkey"},
];
